//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.25 at 09:16:23 PM GMT 
//


package com.ibm.xmlns.prod.cics.events.cbe;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="context-info" type="{http://www.ibm.com/xmlns/prod/cics/events/CBE}contextInfoType"/>
 *         &lt;element name="payload-data" type="{http://www.ibm.com/xmlns/prod/cics/events/CBE}payloadDataType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "contextInfo",
    "payloadData"
})
@XmlRootElement(name = "event", namespace = "http://www.ibm.com/xmlns/prod/cics/events/CBE")
public class Event {

    @XmlElement(name = "context-info", required = true)
    protected ContextInfoType contextInfo;
    @XmlElement(name = "payload-data", required = true)
    protected PayloadDataType payloadData;

    /**
     * Gets the value of the contextInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ContextInfoType }
     *     
     */
    public ContextInfoType getContextInfo() {
        return contextInfo;
    }

    /**
     * Sets the value of the contextInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContextInfoType }
     *     
     */
    public void setContextInfo(ContextInfoType value) {
        this.contextInfo = value;
    }

    /**
     * Gets the value of the payloadData property.
     * 
     * @return
     *     possible object is
     *     {@link PayloadDataType }
     *     
     */
    public PayloadDataType getPayloadData() {
        return payloadData;
    }

    /**
     * Sets the value of the payloadData property.
     * 
     * @param value
     *     allowed object is
     *     {@link PayloadDataType }
     *     
     */
    public void setPayloadData(PayloadDataType value) {
        this.payloadData = value;
    }

}
