//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.25 at 09:16:23 PM GMT 
//


package com.ibm.xmlns.prod.cics.events.cbe;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for contextInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="contextInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="eventname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="usertag" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="networkapplid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="timestamp" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="bindingname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="capturespecname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="UOWid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "contextInfoType", propOrder = {
    "eventname",
    "usertag",
    "networkapplid",
    "timestamp",
    "bindingname",
    "capturespecname",
    "uoWid"
})
public class ContextInfoType {

    @XmlElement(required = true)
    protected String eventname;
    @XmlElement(required = true)
    protected String usertag;
    @XmlElement(required = true)
    protected String networkapplid;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timestamp;
    @XmlElement(required = true)
    protected String bindingname;
    @XmlElement(required = true)
    protected String capturespecname;
    @XmlElement(name = "UOWid", required = true)
    protected String uoWid;

    /**
     * Gets the value of the eventname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventname() {
        return eventname;
    }

    /**
     * Sets the value of the eventname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventname(String value) {
        this.eventname = value;
    }

    /**
     * Gets the value of the usertag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsertag() {
        return usertag;
    }

    /**
     * Sets the value of the usertag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsertag(String value) {
        this.usertag = value;
    }

    /**
     * Gets the value of the networkapplid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNetworkapplid() {
        return networkapplid;
    }

    /**
     * Sets the value of the networkapplid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNetworkapplid(String value) {
        this.networkapplid = value;
    }

    /**
     * Gets the value of the timestamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the value of the timestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimestamp(XMLGregorianCalendar value) {
        this.timestamp = value;
    }

    /**
     * Gets the value of the bindingname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBindingname() {
        return bindingname;
    }

    /**
     * Sets the value of the bindingname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBindingname(String value) {
        this.bindingname = value;
    }

    /**
     * Gets the value of the capturespecname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCapturespecname() {
        return capturespecname;
    }

    /**
     * Sets the value of the capturespecname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCapturespecname(String value) {
        this.capturespecname = value;
    }

    /**
     * Gets the value of the uoWid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUOWid() {
        return uoWid;
    }

    /**
     * Sets the value of the uoWid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUOWid(String value) {
        this.uoWid = value;
    }

}
